[project]
name = "CarrotAgent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "dotenv>=0.9.9",
    "en-core-web-sm",
    "google-search-results>=2.4.2",
    "huggingface-hub>=1.6.0",
    "langchain-openai>=1.1.11",
    "langgraph>=1.1.0",
    "neo4j>=6.1.0",
    "openai>=2.26.0",
    "pydantic-settings>=2.13.1",
    "qdrant-client==1.6.0",
    "spacy>=3.8.11",
    "tavily>=1.1.0",
    "tiktoken>=0.12.0",
    "zh-core-web-sm",
]

[tool.uv.sources]
zh-core-web-sm = { path = "packages/zh_core_web_sm-3.8.0-py3-none-any.whl" }
en-core-web-sm = { path = "packages/en_core_web_sm-3.8.0-py3-none-any.whl" }
